name: PR Code Quality Checks
on:
  push:
    branches:
    - main
    - release/**
  pull_request:
  - main
  - release/**
  workflow_dispatch:
# Cancel old runs when a new commit is pushed to the same branch if not on main or dev
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  code-quality:
    uses: mosaicml/composer/.github/workflows/code-quality.yaml@v0.18.1
    strategy:
      matrix:
        python_version:
        - '3.9'
        - '3.10'
        pip_deps:
        - '[dev]'
    with:
      python_version: ${{ matrix.python_version }}
      pip_deps: ${{ matrix.pip_deps }}
